### PR TITLE
Adds Builds#create_build

### PR DESCRIPTION
**Pull request by es**
`Builds#create_build` will be used by Spy to start a new Tophat build.

r: @byroot @karanthukral

### CODE REVIEW

**Comment by es** [comment]
CI is now :green_heart:

**Comment by byroot** [comment]
LGTM. Might want to add a little confirmation message / error message if all goes right / wrong.

Also a link to the shop if possible.

**Comment by es** [comment]
The link to the shop will be sent in a webhook to Spy after the Tophat instance starts (until then, there's no way to know what agent it will run on).

**Comment by byroot** [comment]
Oh right :facepalm:. So then since it's not immediate, a confirmation message is even more important IMO.

**Comment by es** [comment]
A confirmation message of `:tophat: instance started. You'll recieve a URL shortly` is sent once the build is started.

**Pull request merged**
